"use client";
import Link from "next/link";import {useEffect,useState} from "react";import {currentUser,loadCloudPrefs,saveCloudPrefs} from "@/lib/cloud";
const KEY="remoteflow-alert-preferences";
const defaultPrefs={email:"",categories:["all"],locations:["all"],freshOnly:true,enabled:true};
export default function Alerts(){const[channelUrl]="https://t.me/jobfrsher";const[prefs,setPrefs]=useState(defaultPrefs);const[saved,setSaved]=useState(false);const[cloud,setCloud]=useState(false);
useEffect(()=>{(async()=>{const u=await currentUser();setCloud(!!u);if(u){const p:any=await loadCloudPrefs();if(p)setPrefs({...defaultPrefs,email:p.email||"",categories:p.categories||["all"],locations:p.locations||["all"],freshOnly:p.fresh_only,enabled:p.enabled});}else try{const stored=JSON.parse(localStorage.getItem(KEY)||"null");if(stored)setPrefs({...defaultPrefs,...stored});}catch{}})();},[]);
function persist(){if(cloud)saveCloudPrefs(prefs);else localStorage.setItem(KEY,JSON.stringify(prefs));setSaved(true);setTimeout(()=>setSaved(false),1800);}
function toggle(list:"categories"|"locations",value:string){setPrefs(p=>({...p,[list]:p[list].includes(value)?p[list].filter(v=>v!==value):[...p[list].filter(v=>v!=="all"),value]}));}
return <main className="auth"><Link className="backLink" href="/">← Board</Link><span>Boarding pass · Alerts</span><h1>Never miss<br/>a new arrival.</h1><p>Choose what you want to hear about. {cloud?"Preferences sync securely with your account.":"Sign in to sync preferences across devices."} Telegram delivers the live public feed.</p>
<div className="ticket"><div className="ticketMain"><label>Delivery channel<br/><span className="matchScore">Telegram</span></label><p style={{fontSize:13,color:"var(--ink-dim)",marginTop:14,lineHeight:1.6}}>Every role that clears the fresher filter can be broadcast as the board updates.</p><div className="alertChoices"><p>Categories</p><div>{["all","software","ai","data","design","mobile","devops","marketing","security","product"].map(v=><button key={v} className={"miniChip "+(prefs.categories.includes(v)?"miniChipActive":"")} onClick={()=>toggle("categories",v)}>{v==="all"?"All roles":v}</button>)}</div><p>Locations</p><div>{["all","Worldwide","India","USA Only","Europe","APAC"].map(v=><button key={v} className={"miniChip "+(prefs.locations.includes(v)?"miniChipActive":"")} onClick={()=>toggle("locations",v)}>{v==="all"?"Anywhere":v}</button>)}</div><label className="toggleLine"><input type="checkbox" checked={prefs.freshOnly} onChange={e=>setPrefs(p=>({...p,freshOnly:e.target.checked}))}/> Fresh roles only</label><button className="savePrefs" onClick={persist}>{saved?"✓ Preferences saved":"Save preferences"}</button></div></div><div className="ticketStub"><a className="ticketBtn" href={channelUrl} target="_blank" rel="noopener noreferrer">🔔 Join Telegram Alerts</a><small>Live channel delivery</small></div></div>
<div className="emailComing"><div><p className="eyebrow">EMAIL ALERTS</p><h2>Personal email delivery is next.</h2><p>Phase 4 stores your alert preferences now. Account-based email delivery can be connected without changing your filters later.</p></div><div className="emailMock"><input placeholder="you@example.com" disabled/><button disabled>Coming soon</button></div></div></main>;}