"use client";
import Link from "next/link";import {FormEvent,useEffect,useMemo,useState} from "react";
type App={id:string;job:{title:string;company:string;url?:string};status:string;date:string;notes:string;updatedAt:string};
const KEY="remoteflow-applications-v2",LEGACY="remoteflow-applications",STATUSES=["Saved","Applied","Interview","Offer","Rejected"];
function readApps():App[]{try{return JSON.parse(localStorage.getItem(KEY)||localStorage.getItem(LEGACY)||"[]");}catch{return[]}}
export default function ApplicationsPage(){const[items,setItems]=useState<App[]>([]);const[showForm,setShowForm]=useState(false);const[editing,setEditing]=useState<string|null>(null);
useEffect(()=>setItems(readApps()),[]);
function persist(next:App[]){setItems(next);localStorage.setItem(KEY,JSON.stringify(next));}
function add(e:FormEvent<HTMLFormElement>){e.preventDefault();const fd=new FormData(e.currentTarget);const title=String(fd.get("title")||"").trim(),company=String(fd.get("company")||"").trim();if(!title||!company)return;const now=new Date().toISOString();persist([{id:crypto.randomUUID(),job:{title,company,url:String(fd.get("url")||"")},status:String(fd.get("status")||"Applied"),date:String(fd.get("date")||now.slice(0,10)),notes:String(fd.get("notes")||""),updatedAt:now},...items]);e.currentTarget.reset();setShowForm(false);}
function update(id:string,patch:Partial<App>){persist(items.map(item=>item.id===id?{...item,...patch,updatedAt:new Date().toISOString()}:item));}
function remove(id:string){if(confirm("Remove this application from your tracker?"))persist(items.filter(item=>item.id!==id));}
const stats=useMemo(()=>Object.fromEntries(STATUSES.map(s=>[s,items.filter(i=>i.status===s).length])),[items]);const applied=items.filter(i=>i.status==="Applied"||i.status==="Interview"||i.status==="Offer").length;
return <main className="detailPage"><header className="boardHeader"><Link className="brand" href="/"><span className="brandMark">✈</span>RemoteFlow</Link><div className="headerNav"><Link className="alertLink" href="/saved">Saved</Link><Link className="alertLink" href="/alerts">Alerts</Link></div></header>
<section className="savedPage"><div className="trackerHero"><div><p className="eyebrow">JOB HUNT PIPELINE</p><h1>Applications</h1><p className="savedIntro">Keep every opportunity, interview, note and next step in one place.</p></div><button className="applyButton" onClick={()=>setShowForm(!showForm)}>+ Add application</button></div>
<div className="trackerStats"><div><b>{items.length}</b><span>Total</span></div><div><b>{applied}</b><span>Active</span></div><div><b>{stats.Interview||0}</b><span>Interviews</span></div><div><b>{stats.Offer||0}</b><span>Offers</span></div></div>
{showForm&&<form className="applicationForm" onSubmit={add}><input name="title" placeholder="Job title *" required/><input name="company" placeholder="Company *" required/><input name="url" placeholder="Application URL (optional)" type="url"/><select name="status">{STATUSES.map(s=><option key={s}>{s}</option>)}</select><input name="date" type="date" defaultValue={new Date().toISOString().slice(0,10)}/><textarea name="notes" placeholder="Notes, recruiter name, interview details…"/><div><button className="applyButton" type="submit">Add to tracker</button><button className="saveButton" type="button" onClick={()=>setShowForm(false)}>Cancel</button></div></form>}
<div className="tracker">{STATUSES.map(status=><div className="trackerColumn" key={status}><h3>{status}<span>{stats[status]||0}</span></h3>{items.filter(i=>i.status===status).map(item=><article className="trackerCard trackerCardFull" key={item.id}><strong>{item.job.title}</strong><span>{item.job.company}</span><small>Added {item.date}</small>{item.notes&&<p>{item.notes}</p>}<select value={item.status} onChange={e=>update(item.id,{status:e.target.value})}>{STATUSES.map(s=><option key={s}>{s}</option>)}</select><div className="cardActions">{item.job.url&&<a href={item.job.url} target="_blank" rel="noreferrer">Open ↗</a>}<button onClick={()=>setEditing(editing===item.id?null:item.id)}>Notes</button><button onClick={()=>remove(item.id)}>Remove</button></div>{editing===item.id&&<textarea className="inlineNotes" value={item.notes} placeholder="Add notes…" onChange={e=>update(item.id,{notes:e.target.value})}/>}</article>)}</div>)}</div>
{items.length===0&&<div className="empty"><h3>Your tracker is ready for takeoff.</h3><p>Add your first application or discover opportunities from the board.</p><Link className="chip chipActive" href="/">Explore jobs</Link></div>}</section></main>;}