"use client";
import {supabase} from "@/lib/supabase";

export type CloudJob={id:string;title:string;company:string;location:string;url:string;source:string;publishedAt?:string};
export type CloudApplication={id:string;job:{title:string;company:string;url?:string};status:string;date:string;notes:string;updatedAt:string;nextAction?:string;nextActionDate?:string};

type SavedJobRow={job_id:string;title:string;company:string;location:string;url:string;source:string;published_at:string|null};
type ApplicationRow={id:string;title:string;company:string;url?:string;status:string;application_date:string;notes?:string;updated_at:string;next_action?:string;next_action_date?:string};
type CloudPrefs={email?:string;categories:string[];locations:string[];fresh_only:boolean;enabled:boolean};

export async function currentUser(){if(!supabase)return null;const{data}=await supabase.auth.getUser();return data.user||null;}
export async function loadCloudSaved(){const u=await currentUser();if(!u||!supabase)return null;const{data}=await supabase.from("user_saved_jobs").select("job_id,title,company,location,url,source,published_at").eq("user_id",u.id).order("created_at",{ascending:false});if(!data)return[];return(data as SavedJobRow[]).map(x=>({id:x.job_id,title:x.title,company:x.company,location:x.location,url:x.url,source:x.source,publishedAt:x.published_at??undefined}));}
export async function toggleCloudSaved(job:CloudJob){const u=await currentUser();if(!u||!supabase)return null;const{data:existing}=await supabase.from("user_saved_jobs").select("job_id").eq("user_id",u.id).eq("job_id",job.id).maybeSingle();if(existing){await supabase.from("user_saved_jobs").delete().eq("user_id",u.id).eq("job_id",job.id);return false;}await supabase.from("user_saved_jobs").upsert({user_id:u.id,job_id:job.id,title:job.title,company:job.company,location:job.location,url:job.url,source:job.source,published_at:job.publishedAt||null},{onConflict:"user_id,job_id"});return true;}
export async function loadCloudApps(){const u=await currentUser();if(!u||!supabase)return null;const{data}=await supabase.from("user_applications").select("*").eq("user_id",u.id).order("updated_at",{ascending:false});return(data||[]).map((x:ApplicationRow)=>({id:x.id,job:{title:x.title,company:x.company,url:x.url||""},status:x.status,date:x.application_date,notes:x.notes||"",updatedAt:x.updated_at,nextAction:x.next_action||"",nextActionDate:x.next_action_date||""}));}
export async function saveCloudApps(items:CloudApplication[]){const u=await currentUser();if(!u||!supabase)return false;const rows=items.map(x=>({id:x.id,user_id:u.id,title:x.job.title,company:x.job.company,url:x.job.url||null,status:x.status,application_date:x.date,notes:x.notes||"",next_action:x.nextAction||null,next_action_date:x.nextActionDate||null,updated_at:x.updatedAt}));if(rows.length)await supabase.from("user_applications").upsert(rows,{onConflict:"id"});return true;}
export async function loadCloudPrefs(){const u=await currentUser();if(!u||!supabase)return null;const{data}=await supabase.from("user_alert_preferences").select("*").eq("user_id",u.id).maybeSingle();return data as CloudPrefs|null;}
export async function saveCloudPrefs(p:CloudPrefs){const u=await currentUser();if(!u||!supabase)return false;await supabase.from("user_alert_preferences").upsert({user_id:u.id,email:p.email||null,categories:p.categories,locations:p.locations,fresh_only:p.fresh_only,enabled:p.enabled,updated_at:new Date().toISOString()},{onConflict:"user_id"});return true;}